name: Build and Deploy Backend and Frontend using GHCR

on:
  push:
    branches:
      - "*" # Für alle Branches
  pull_request:
    branches:
      - "*" # Für Pull Requests auf alle Branches

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Backend with Gradle
        run: |
          cd backend
          gradle build

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Images
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend
          docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend

      - name: Push Docker Images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

      - name: Deploy with Docker Compose
        env:
          BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/backend:latest
          FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/frontend:latest
        run: |
          docker-compose down || true
          docker-compose up -d
