name: Build and Deploy Backend and Frontend using GHCR

on:
  push:
    branches:
      - "*" # Für alle Branches
  pull_request:
    branches:
      - "*" # Für Pull Requests auf alle Branches
  workflow_dispatch: # Manuelles Triggern erlauben

jobs:
  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build Backend
      - name: Build Backend with Gradle
        run: |
          cd backend
          gradle build

      # 4. Build Docker Image for Backend
      - name: Build Backend Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend

      # 5. Push Backend Docker Image
      - name: Push Backend Docker Image
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # 5. Verify react-scripts Installation
      - name: Verify react-scripts Installation
        run: |
          cd frontend
          npm list react-scripts

      # 6. Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # 7. Build Docker Image for Frontend
      - name: Build Frontend Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner | toLowerCase }}/frontend:latest ./frontend

      # 8. Push Frontend Docker Image
      - name: Push Frontend Docker Image
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker push ghcr.io/${{ github.repository_owner | toLowerCase }}/frontend:latest

  deploy:
    name: Deploy Application
    needs:
      - backend-build
      - frontend-build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Deploy with Docker Compose
      - name: Deploy with Docker Compose
        env:
          BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/backend:latest
          FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/frontend:latest
        run: |
          docker-compose down || true
          docker-compose up -d
